"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# -------------------------------------------------------------------
# PATH CONFIGURATION
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------------
# SECURITY SETTINGS
# -------------------------------------------------------------------

SECRET_KEY = 'django-insecure-g=$g%8%1@(441xujplb=3^aafvlu7c(=^oi_j)bi2hmj3he94z'

DEBUG = True

ALLOWED_HOSTS = []


# SECURITY: set via env in production
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-secret-key-for-local')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# --- Security hardening ---
SECURE_BROWSER_XSS_FILTER = True                # enable browser XSS filter
X_FRAME_OPTIONS = 'DENY'                        # prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True              # prevent MIME sniffing

# Cookies: enforce HTTPS in production
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# --- HTTPS / security-related settings (paste into settings.py) ---

# Debug controlled by env var. In production set DJANGO_DEBUG=False
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Use environment var for allowed hosts in production
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Redirect all HTTP to HTTPS (enable in production)
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "False") == "True"

# HSTS: tells browsers to only use HTTPS for this domain
# Use a small value during rollout (e.g. 3600) then increase to 31536000 (1 year)
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True") == "True"
SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "True") == "True"

# Cookies: only send cookies over HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # leaving False is common so client-side scripts can still access CSRF if needed


# Common browser protections
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# If running behind a proxy/load balancer that terminates TLS (e.g. nginx or ELB)
# instruct Django to trust the X-Forwarded-Proto header.
# Only set this if you actually use a proxy that sets this header!
# In production: os.environ['DJANGO_SECURE_PROXY_HEADER'] = 'HTTP_X_FORWARDED_PROTO'
if os.environ.get("DJANGO_SECURE_PROXY_SSL_HEADER", "False") == "True":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# --- end HTTPS/security settings ---



CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "img-src": ("'self'", "data:"),
        "script-src": ("'self'",),
        "style-src": ("'self'", "https://fonts.googleapis.com"),
        "font-src": ("'self'", "https://fonts.gstatic.com"),
    }
}




# -------------------------------------------------------------------
# APPLICATION DEFINITION
# -------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Your apps
    'relationship_app',   # existing app
    'accounts',           # new app for custom user model
    'bookshelf',          # optional additional app (if used)
    'csp',  # add to installed apps
]

# Use the custom user model
'''AUTH_USER_MODEL = 'accounts.CustomUser'''
AUTH_USER_MODEL = 'bookshelf.CustomUser'



MIDDLEWARE = [
    'LibraryProject.middleware.SimpleCSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'LibraryProject.middleware_security.SecurityHeadersMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # early in middleware stack
]


ROOT_URLCONF = 'LibraryProject.urls'




# -------------------------------------------------------------------
# TEMPLATES
# -------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ✅ project-level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# -------------------------------------------------------------------
# DATABASE CONFIGURATION
# -------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -------------------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -------------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------------------------------------------------------
# STATIC & MEDIA FILES
# -------------------------------------------------------------------

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # ✅ use Pathlib, not os.path


# -------------------------------------------------------------------
# LOGIN / LOGOUT REDIRECTS
# -------------------------------------------------------------------

LOGIN_REDIRECT_URL = 'list_books'
LOGOUT_REDIRECT_URL = 'login'


# -------------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
